import os
from langchain.chat_models import init_chat_model
from langchain.messages import SystemMessage, HumanMessage

"""
This file is for talking to the LLM. I have created a function below
that will help you to generate a recipe using the ingredients provided.
Use the function model_generate_recipe to generate a recipe.

NOTE: The function is a generator function. It YIELDS and NOT RETURNS.
Read about generator functions and STREAMING. A bit of research will help you a lot. 
Feel free to ask your doubts if you have any.
"""

model = init_chat_model("google_genai:gemini-2.5-flash-lite")


def model_generate_recipe(ingredients: List[str], cuisines: str):
    """
    This function is used to generate a recipe of a particular cuisine using the ingredients provided.

    Args:
        ingredients (List[str]): List of ingredients to be used in the recipe.
        cuisines (str): Cuisine of the recipe.
    
    Yields:
        str: Recipe generated by the model.
    """
    system_prompt = f"""
        You are an expert chef with 20 years of experience in cooking. You are knowledgeable in all cuisines and can create delicious recipes using the ingredients provided.
        You can use all the ingredients or some of the ingredients from the list of ingredients provided.
        Here is the list of ingredients: {ingredients}
        Provide a recipe in {cuisines} cuisine.

        # Output Format : 
        Recipe Name: <name>
        Ingredients used: <ingredients>
        How to cook: <steps> in points.
        """
    conversation = [
        SystemMessage(content=system_prompt), 
        HumanMessage(content="Provide a delicious recipe using the ingredients provided.")
        ]
    for chunk in model.stream(conversation):
        yield chunk.text